### ISSUE TITLE
How to Get the First Frame of Video

### ISSUE THREAD

**Issue by liurui12w** [avlos/ffprobe#2]
How do I extract the first frame of the video file to make the cover image? Is there any relevant method?

**Comment by shamangeorge** [comment]
Hi,

as far as I know there are no ways to extract the frame (in image format) of the video using `ffprobe`. You would have to use `ffmpeg` to get that. You can, however, extract metadata information about the frame using `ffprobe`. Currently this gem only returns metadata information about the video itself and nothing relating to its frames. 

There is more information in [this](https://superuser.com/questions/885452/extracting-the-index-of-key-frames-from-a-video-using-ffmpeg) thread about how to extract frames and their info using `ffprobe` along with `ffmpeg`. This is an interesting use case for us as well so we will try to extend the gem functionality to support this.

**Comment by liurui12w** [comment]
> Hi,
> 
> as far as I know there are no ways to extract the frame (in image format) of the video using `ffprobe`. You would have to use `ffmpeg` to get that. You can, however, extract metadata information about the frame using `ffprobe`. Currently this gem only returns metadata information about the video itself and nothing relating to its frames.
> 
> There is more information in [this](https://superuser.com/questions/885452/extracting-the-index-of-key-frames-from-a-video-using-ffmpeg) thread about how to extract frames and their info using `ffprobe` along with `ffmpeg`. This is an interesting use case for us as well so we will try to extend the gem functionality to support this.

Thank you for your idea.
